### ISSUE TITLE
[FR] Add support for Block Shortcuts syntax

### ISSUE THREAD

**Issue by rungta** [zackad/prettier-plugin-twig#106]
Twig allows a [_Block Shortcuts_ syntax](https://twig.symfony.com/doc/3.x/tags/extends.html#block-shortcuts): 

```twig
{% block title %}
    {{ page_title|title }}
{% endblock %}

{% block title page_title|title %}
```

The plugin doesn't appear to recognise this at the moment.

```
[error] templates/_layouts/base.twig: Error: ERROR: Invalid Token
[error]   26 | #}
[error]   27 | {% block page_main %}
[error] > 28 |   <main class="{% block main_class '' %}">
[error]      |                ^^
[error]   29 |     {% block main %}{% endblock %}
[error]   30 |   </main>
[error]   31 | {% endblock %}
[error] 
[error] Expected stringEnd but found tag start "{%" instead.
[error]     at TokenStream.error (file:///…/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/TokenStream.js:129:24)
[error]     at TokenStream.expect (file:///…/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/TokenStream.js:103:14)
[error]     at Parser.matchAttributes (file:///…/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:413:28)
[error]     at Parser.matchElement (file:///…/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:337:14)
[error]     at Parser.parse (file:///…/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:211:32)
[error]     at Object.parse (file:///…/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-extension-core/parser/block.js:42:24)
[error]     at Parser.matchTag (file:///…/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:498:31)
[error]     at Parser.parse (file:///…/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:177:32)
[error]     at Object.parse (file:///…/node_modules/@zackad/prettier-plugin-twig/src/parser.js:82:24)
[error]     at parse4 (file:///…/node_modules/prettier/index.mjs:20724:24)
```

**Comment by zackad** [comment]
The problem with your example is related to GH-61 that block expression in html attribute is not yet supported.

**Comment by zackad** [comment]
It turns out that block shortcut syntax has been supported. I fix printing string literal as block body value when using shortcut syntax.
