### ISSUE TITLE
Parser doesn't allow <body {% block body_attributes %}{% endblock %}>

### ISSUE THREAD

**Issue by jraller** [zackad/prettier-plugin-twig#61]
A twig template with

```
    <body {% block body_attributes %}{% endblock %}>
        {% block body %}
        {% endblock %}
    </body>
```

in it passes the linter `symfony console lint:twig templates`, but prettier-plugin-twig's parser reports:

>[error] templates/base.html.twig: Error: ERROR: Invalid token
[error]   18 |         {% endblock %}
[error]   19 |     </head>
[error] > 20 |     <body {% block body_attributes %}{% endblock %}>
[error]      |           ^
[error]   21 |         {% block body %}
[error]   22 |         {% endblock %}
[error]   23 |     </body>
[error]
[error] A tag must consist of attributes or expressions. Twig Tags are not allowed.
[error]     at TokenStream.error (file:///C:/Users/Jason/AppData/Roaming/npm/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/TokenStream.js:129:24)
[error]     at Parser.error (file:///C:/Users/Jason/AppData/Roaming/npm/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:452:21)
[error]     at Parser.matchAttributes (file:///C:/Users/Jason/AppData/Roaming/npm/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:442:22)
[error]     at Parser.matchElement (file:///C:/Users/Jason/AppData/Roaming/npm/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:333:14)
[error]     at Parser.parse (file:///C:/Users/Jason/AppData/Roaming/npm/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:207:32)
[error]     at Parser.matchElement (file:///C:/Users/Jason/AppData/Roaming/npm/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:343:41)
[error]     at Parser.parse (file:///C:/Users/Jason/AppData/Roaming/npm/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:207:32)
[error]     at Object.parse (file:///C:/Users/Jason/AppData/Roaming/npm/node_modules/@zackad/prettier-plugin-twig/src/parser.js:82:24)     
[error]     at parse4 (file:///C:/Users/Jason/AppData/Roaming/npm/node_modules/prettier/index.mjs:20685:24)
[error]     at async coreFormat (file:///C:/Users/Jason/AppData/Roaming/npm/node_modules/prettier/index.mjs:21146:7)

usage for this when calling the body_attributes block allows for passing in class and data-controller as follows:

```
{% block body_attributes %}
    class="bg-gray-100 font-sans leading-normal tracking-normal mt-12" data-controller="style"'%}
{% endblock %}
```

**Comment by jraller** [comment]
It looks like this dates back to https://github.com/trivago/prettier-plugin-twig-melody/issues/60

**Comment by zackad** [comment]
I'm not sure how to tackle this issue. Adding support for twig tag inside html element might not be complicated. Example
```twig
<div {% block class %}class="hidden"{% endblock class %}>
</div>
```
On the other hand, if we need to imlement support for twig tag inside attribute value, example
```twig
<div class="{% block class %}hidden{% endblock class %}">
</div>
```
the parser logic will be significantly more complex.

Ideally, all twig features should be supported. However we lack the skill to actually implement this features.

Should we partially implement this feature, allow twig tag inside html element? Skipping twig tag inside html attribute value. Or don't bother to add this feature if not fully implemented? Waiting for feedback.

**Comment by Levdbas** [comment]
I think there are way more elegant solutions this, like using an extension like: https://github.com/parisek/twig-attribute. And then just setting the variable that sets all the attributes via the child template.

**Comment by zackad** [comment]
TBH, I'm not a big fan of using twig tag inside html element. There's other solution that I think more elegant, such as using extension like example above or using something like [twig-component](https://symfony.com/bundles/ux-twig-component/current/index.html).

In my experience, the usage of block expression on html attribute can be achived using ternary expression (which this plugin supported) in some cases. And so far I can live without this feature.

Unless there's strong opinion that this should be implemented, I don't want to add this feature. Feel free to send pull request. Maybe I can work from there.

Thanks.

**Comment by renestalder** [comment]
I don't know what the non-existing specification (not even joking here) of Twig says about this. But in my advanced experience building with Twig, using `block` inside the HTML tags was never a solution for something that I couldn't have done otherwise. I saw this in use for the first time when reviewing Twig code written by sole PHP developers. I'm not a PHP developer, so I might not necessarily understand the background to this approach. I only write frontend code and I do this most of the time in Twig. So, I might be able to give some inputs on how this can be done in a way it is more readable anyway.

Here are the (mostly better) alternatives for this, from my point of view:

- **Using variables**: Simply passing this down as a variable and rendering it with the `|raw` pipe, and if you want so for security, the `|e` pipe, is more readable in any case.
- **Using the block function**: For example in your case ```{{ block('class') }}```.
- **Pass down a key/value structure and add your own function to Twig to render it as an attribute-key/value string**. I've done somethig like this with Twig Macros because my limited PHP understanding. But adding a function to Twig is pretty straight forward.
- **Install Symfony extensions**: Like in the case of `class`, the HTML Extras and Extra-Bundles with the [`html_classes` function](https://twig.symfony.com/doc/3.x/functions/html_classes.html) is the cleanest approach.

Or as @zackad said, the Twig Components from Symfony's UX initiative. In case you are anyway in the Symfony ecosystem.

(my 50 cents as a Twig user using the Prettier formatter)

**Comment by ryanleichty** [comment]
Just installed this in order to test it and this is the first thing I ran into. We use twig tags like this everywhere, so converting everything isn't a small task and probably not a goal of ours. I know [liquid supports tags like this](https://github.com/Shopify/dawn/blob/main/layout/theme.liquid) and they have a prettier plugin as well.

**Comment by MangoMarcus** [comment]
Getting the same issue too eg.

```twig
<picture
    {% if pictureClasses %}
        class="{{ pictureClasses }}"
    {% endif %}
>
```

and with comments

```twig
<button
    type="button"
    {# Some comment here #}
    class="flex-shrink-0 size-6 grid place-items-center"
>
    Foo
</button>
```

**Comment by andyexeter** [comment]
We forked Shopify's Liquid Prettier plugin to create our own Twig plugin and it supports this syntax: https://github.com/wearedestination/prettier-plugin-twig
