### ISSUE TITLE
Errors when using macros

### ISSUE THREAD

**Issue by lexisother** [zackad/prettier-plugin-twig#68]
I'm getting an error regarding attributes when using HTML tags within a macro.

```
[error] templates/_includes/fonts.twig: Error: ERROR: Expected an Identifier
[error]   1 | {% apply spaceless %}
[error]   2 |     {% macro google(href) %}
[error] > 3 |         <link rel='preconnect' href='https://fonts.googleapis.com'>
[error]     |                   ^
[error]   4 |         <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin>
[error]   5 |         <link href='{{ href }}' rel='stylesheet'>
[error]   6 |     {% endmacro %}
[error]
[error] Expected a valid attribute name, but instead found "'", which is not part of a valid attribute name.
[error]     at TokenStream.error (file:///var/www/html/node_modules/.pnpm/@zackad+prettier-plugin-twig@0.9.1/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/TokenStream.js:129:24)
[error]     at new TokenStream (file:///var/www/html/node_modules/.pnpm/@zackad+prettier-plugin-twig@0.9.1/node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/TokenStream.js:59:18)
[error]     at createConfiguredParser (file:///var/www/html/node_modules/.pnpm/@zackad+prettier-plugin-twig@0.9.1/node_modules/@zackad/prettier-plugin-twig/src/parser.js:51:9)
[error]     at Object.parse (file:///var/www/html/node_modules/.pnpm/@zackad+prettier-plugin-twig@0.9.1/node_modules/@zackad/prettier-plugin-twig/src/parser.js:81:20)
[error]     at parse4 (file:///var/www/html/node_modules/.pnpm/prettier@3.3.3/node_modules/prettier/index.mjs:20685:24)
[error]     at async coreFormat (file:///var/www/html/node_modules/.pnpm/prettier@3.3.3/node_modules/prettier/index.mjs:21146:7)
[error]     at async formatWithCursor (file:///var/www/html/node_modules/.pnpm/prettier@3.3.3/node_modules/prettier/index.mjs:21348:14)
[error]     at async formatFiles (file:///var/www/html/node_modules/.pnpm/prettier@3.3.3/node_modules/prettier/internal/cli.mjs:3468:18)
[error]     at async main (file:///var/www/html/node_modules/.pnpm/prettier@3.3.3/node_modules/prettier/internal/cli.mjs:3876:5)
[error]     at async Module.run (file:///var/www/html/node_modules/.pnpm/prettier@3.3.3/node_modules/prettier/internal/cli.mjs:3822:5)
```

**Comment by lexisother** [comment]
Whoops, seems this is simply the issue of me using single quotes instead of double quotes.
